[package]
name = "devops-test"
version = "0.1.0"
authors = ["punxx-76 <pespyc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
